config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "trains#index"
  resources :trains do
    resources :sheets
     resources :orders
  end
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :sheet
end

app/models/sheet.rb
class Sheet < ApplicationRecord
  belongs_to :buyer, class_name: 'User', foreign_key: 'buyer_id', optional: true
  belongs_to :seller, class_name: 'User', foreign_key: 'seller_id'
  belongs_to :train
end

app/models/train.rb
class Train < ApplicationRecord
  
  has_many :sheets
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  validates :paypay_account, presence: true
  has_many :sheets

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :paypay_account])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :paypay_account])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new

    @sheet = Sheet.find_by(id: params[:sheet_id])
  end
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
   before_action :authenticate_user!, except: [:index]
 
   def show
      @sheet = Sheet.find_by(id: params[:id])
      if @sheet.nil?
        # シートがまだ存在しない場合、新しいシートインスタンスを作成
        @sheet = Sheet.new
        render :new  # sheet/new.html.erb をレンダリングする
        return
      end
    end
 
    def new
      @train = Train.find(params[:train_id])
      @sheet = Sheet.new
    end
    
    def create
      @train = Train.find(params[:train_id])
      @sheet = @train.sheets.build(sheet_params)
      @sheet.seller_id = current_user.id  # seller_id に現在のユーザーのIDを設定
      @sheet.buyer_id = nil  # buyer_id は初期状態では設定しない
      # buyer_id は購入時に設定するので、ここでは設定しない
      if @sheet.save
        redirect_to train_sheet_path(@train, @sheet), notice: 'シートを出品しました。'
      else
         logger.error @sheet.errors.full_messages  # ここを追加
        flash.now[:alert] = @sheet.errors.full_messages.join(",入力に不備があります ")
        render :new
      end
    end
    
    def destroy
      @sheet = Sheet.find_by(id: params[:id])
      unless @sheet
        redirect_to root_path, alert: 'シートが見つかりません'
        return
      end
    
      if @sheet.seller_id == current_user.id
        @sheet.destroy
      end
      redirect_to root_path
    end


   def update
     @sheet = Sheet.find_by(id: params[:id])
     unless @sheet
       redirect_to root_path, alert: 'シートが見つかりません'
       return
     end
 
     if @sheet.update(sheet_params)
       redirect_to sheet_path(@sheet), notice: '情報を更新しました。'
     else
       render :show
     end
   end
 
   def purchase
     @seat = Seat.find_by(id: params[:id])
     unless @seat
       redirect_to root_path, alert: '席が見つかりません'
       return
     end
 
     if @seat.status == "available"
       @seat.update(user_id: current_user.id, status: "purchased")
       redirect_to @seat, notice: '席を購入しました。'
     else
       redirect_to @seat, alert: '席は既に購入されています。'
     end
   end
 
   private
   
   def sheet_params
      params.require(:sheet).permit(:exit_station, :appearance, :seat_number)
    end
 end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  def index

    @trains = Train.all
  end

    @number_of_trains = 11
    @trains = Train.limit(@number_of_trains)


  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  RADIUS = 0.1 # 100m以内のユーザーを検索

  def nearby_users
    @users = User.where("ST_Distance_Sphere(point(longitude, latitude), point(?, ?)) < ?", params[:lon], params[:lat], RADIUS * 1000)
    render json: @users
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper

  def new
  end
  
end

app/helpers/sheet_helper.rb
module SheetHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
  def left_value_for(seat_number)
    # ここで席番号に応じて左の値を計算して返す
    [0, 0, 0, 70, 70, 70][seat_number - 1]
  end

  def top_value_for(seat_number)
    # ここで席番号に応じて上の値を計算して返す
    [27, 50, 73, 27, 50, 73][seat_number - 1]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>席探 -山手線-</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
     <div class="header2">
          </div>
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
           
          </div>

      <%# // ログインしているときは下記を表示 %>
          <% if user_signed_in? %>
             <div class="nav__right"> 
               <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__btn %>
             

                <%# ログインしているときはようこそ〜表示 %>
         <% if user_signed_in? %>
           <div class="greeting">
        <%= "ようこそ、"%>
         <%= link_to "#{current_user.nickname}さん", root_path, class: :greeting__link %>
           </div> 
            <% end %>
             <%# // ログインしているときはようこそ〜表示 %>
 </div> 
             <%# // ログインしているときは上記を表示 %>
          <% else %>
          <%# ログインしていないときは以下を表示 %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
            <% end %>
          <%# // ログインしていないときは上記を表示 %>    
        </div>
        
       </div>
    </header>
        <%= yield %>

 


    <footer class="footer">
     <div class="footer2">
      <p class="copyright">Copyright©2023 席探 -山手線- All Rights Reserved.</p>
      </div>
    </footer>
  </body>
</html>

app/views/orders/new.html.erb
<div class="order_new">
  <div class="sheet_font1">このシートを100円で購入します</div>
  <div class="sheet_font2">出品者の特徴は <b><%= @sheet&.appearance || "未設定" %></b> です</div>
  <div class="sheet_font2">カメラでpaypayバーコードを読みとって支払いをおこなってください</div>
  <div class="sheet_font2">決済完了したのち目的の駅に着いたら座席を交代してください</div>

<div class="camera">
  <div id="cam">
    <label for="upload">カメラを起動する</label>
    <input id="upload" class="camera-input" type="file" name="image" accept="image/*" capture>
</div>
</div>
</div>

app/views/sheets/new.html.erb
<%= form_for [@train, @sheet] do |f| %>
  <div class="form-group">
    <%= f.hidden_field :seat_number, value: params[:seat_number] %>
  <br>
      <%= f.label :exit_station, "下車駅　　　" %>
      <%= f.select :exit_station, 
                   ["大崎", "五反田", "目黒","恵比寿", "渋谷", "原宿","代々木", "新宿", "新大久保","高田馬場", "目白", "池袋","大塚", "巣鴨", "駒込","田端","西日暮里", "日暮里", "鶯谷","上野", "御徒町", "秋葉原","神田", "東京", "有楽町","新橋", "浜松町","田町", "高輪ゲートウェイ", "品川"], 
                   { prompt: "駅を選択してください" }, 
                   class: "form-control" %>
    </div>
  <div class="field">
    <%= f.label :服装の特徴等 %>
    <%= f.text_field :appearance %>
  </div>

  <div class="actions">
  <div class="nav__del">
    <%= f.submit "100円シートを作成" %>
  </div>
  </div>
<% end %>

app/views/sheets/show.html.erb
<div class="sheets_show">
<%= image_tag "pay.png", alt: "Pay Image" %>

  <div class="sheet_font1">このシートを出品しました</div>
  
  <div class="sheet_font2">購入者が来たらQRコードを読み取ってもらいましょう</div>
  <div class="sheet_font2">決済完了かつ目的の駅に着いたら座席を購入者と交代してください</div>
  <br>
  <div class="sheet_font2">※キャンセルする場合や購入者が現れなかった場合は下記ボタンからこの座席の出品を取り消してください</div>
  <div class="nav__del"> 
<%= link_to "この座席の出品取消", train_sheet_path(@sheet.train_id, @sheet), method: :delete, class: :nav__btn %>
</div>
</div>

app/views/trains/index.html.erb
<main class="main">
  <div class="inner">
    <div class="info">
      <div class="info1">空席</div>
      <div class="info2">購入可</div>
      <div class="info3">出品中</div>
    </div>
    <div class="card__wrapper">

      <% @trains.each do |train| %>

        <div class="train">
          <div class="yajirushi">⬆️</div> 
          <h1><%= train.id %>号車</h1>
  <div class="door" style="left: 0%; top: 15%;"></div>
  <div class="door" style="left: 0%; top: 38%;"></div>
  <div class="door" style="left: 0%; top: 62%;"></div>
  <div class="door" style="left: 0%; top: 85%;"></div>
  <div class="door" style="right: 0%; top: 15%;"></div>
  <div class="door" style="right: 0%; top: 38%;"></div>
  <div class="door" style="right: 0%; top: 62%;"></div>
  <div class="door" style="right: 0%; top: 85%;"></div>
  

    <% (1..6).each do |seat_number| %>
            <% sheet = train.sheets.find_by(seat_number: seat_number) %>

            <% if sheet.present? && current_user %>
              <% if sheet.seller_id == current_user.id %>
                <!-- 席が出品されており、現在のユーザーが出品者である場合 -->
                <div class="sheet<%= seat_number %> served" style="left: <%= left_value_for(seat_number) %>%; top: <%= top_value_for(seat_number) %>%;">
                  <%= link_to "出品中", train_sheet_path(train, sheet), class: "sheet#{seat_number} info33" %>
                </div>
              <% elsif sheet.seller_id != current_user.id %>
              <!-- 席が出品されており、現在のユーザーが出品者ではない場合 -->
               <div class="sheet<%= seat_number %> reserved" style="left: <%= left_value_for(seat_number) %>%; top: <%= top_value_for(seat_number) %>%;">
                 <%= link_to sheet.exit_station || "購入可", new_train_order_path(train_id: train.id, sheet_id: sheet.id), class: "sheet#{seat_number} info22" %>
               </div>
             <% end %>
            <% else %>
              <!-- 席が出品されていない場合またはログインしていない場合 -->
              <div class="sheet<%= seat_number %>" style="left: <%= left_value_for(seat_number) %>%; top: <%= top_value_for(seat_number) %>%;">
                <%= link_to new_train_sheet_path(train, seat_number: seat_number), class: "sheet#{seat_number}" do %>
                  <!-- 席の内容 -->
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</main>